# Generated by Django 4.2.7 on 2023-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viaggio', models.DateField(default=django.utils.timezone.now)),
                ('distanza_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_viaggio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.IntegerField(choices=[(0, 'Non Fatturato'), (1, 'Fatturato')], default=0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fatture.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('T', 'Tasse'), ('B', 'Burocrazia'), ('C', 'Clienti'), ('S', 'Spese')], max_length=1)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fatture.cliente')),
                ('viaggi', models.ManyToManyField(to='fatture.viaggio')),
            ],
        ),
    ]
