# Generated by Django 4.2.7 on 2023-12-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaggio',
            name='ddt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaggio',
            name='mittente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaggi_mittente', to='fatture.cliente'),
        ),
        migrations.AddField(
            model_name='viaggio',
            name='pagato',
            field=models.IntegerField(choices=[(0, 'Non Pagato'), (1, 'Pagato')], default=0),
        ),
        migrations.AlterField(
            model_name='viaggio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaggi_cliente', to='fatture.cliente'),
        ),
    ]
